import {
  Activity,
  BadgeCheck,
  BatteryCharging,
  Bell,
  Building2,
  ChartLine,
  ChartNoAxesColumn,
  Clock,
  Cloud,
  ClipboardList,
  Cpu,
  Cylinder,
  Droplet,
  Droplets,
  Factory,
  FileText,
  Fuel,
  Gauge,
  Handshake,
  HardHat,
  Headset,
  LayoutDashboard,
  Leaf,
  MapPin,
  Mountain,
  Nfc,
  PlugZap,
  Radio,
  ReceiptText,
  Route,
  ShieldCheck,
  Smartphone,
  TowerControl,
  Tractor,
  Truck,
  Warehouse,
  Workflow,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

/**
 * Icon registry. Content files reference icons by name (a plain string) so the data
 * stays serializable across the server/client boundary.
 */
export const ICONS = {
  activity: Activity,
  badgeCheck: BadgeCheck,
  batteryCharging: BatteryCharging,
  bell: Bell,
  building: Building2,
  chartLine: ChartLine,
  chartBars: ChartNoAxesColumn,
  clipboard: ClipboardList,
  clock: Clock,
  cloud: Cloud,
  cpu: Cpu,
  cylinder: Cylinder,
  droplet: Droplet,
  droplets: Droplets,
  factory: Factory,
  fileText: FileText,
  fuel: Fuel,
  gauge: Gauge,
  handshake: Handshake,
  hardHat: HardHat,
  headset: Headset,
  dashboard: LayoutDashboard,
  leaf: Leaf,
  mapPin: MapPin,
  mountain: Mountain,
  nfc: Nfc,
  plugZap: PlugZap,
  radio: Radio,
  receipt: ReceiptText,
  route: Route,
  shieldCheck: ShieldCheck,
  smartphone: Smartphone,
  tower: TowerControl,
  tractor: Tractor,
  truck: Truck,
  warehouse: Warehouse,
  workflow: Workflow,
  wrench: Wrench,
  zap: Zap,
} satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof ICONS;
