/**
 * Image slot tooling. content/images.ts is the single source of truth; this script only reads it.
 *
 *   node scripts/images.mjs check [--strict]   list missing files + dev placeholders still in place (--strict: exit 1 if any)
 *   node scripts/images.mjs readme             regenerate public/images/README.md
 *   node scripts/images.mjs placeholders       create labelled placeholder .webp files for MISSING slots only
 *   node scripts/images.mjs optimize [--dry]   re-encode REAL photos that exceed the TRD §10 budget (hero <= 200KB, others <= 120KB)
 *
 * Placeholders carry an EXIF marker (PLACEHOLDER_MARK) so `check` can tell them apart from real photos;
 * dropping a real file over one removes the marker. Existing files are never overwritten.
 * Needs Node >= 22.18 (runs content/images.ts through Node's built-in TypeScript type stripping).
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { dirname, join, relative, resolve, sep } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const PUBLIC = join(ROOT, "public");
const IMAGES_DIR = join(PUBLIC, "images");
const PLACEHOLDER_MARK = "INDOX-DEV-PLACEHOLDER";

const { images, imageUsage, IMAGE_FOLDERS } = await import(pathToFileURL(join(ROOT, "content", "images.ts")).href);
const slots = Object.values(images).sort(
  (a, b) => IMAGE_FOLDERS.indexOf(a.folder) - IMAGE_FOLDERS.indexOf(b.folder) || a.key.localeCompare(b.key),
);

const fileOf = (slot) => join(PUBLIC, ...slot.src.split("/").filter(Boolean));
const rel = (path) => relative(ROOT, path).split(sep).join("/");
const ratio = (slot) => slot.aspectRatio.replace(" / ", ":");
const isPlaceholder = (path) => readFileSync(path).includes(PLACEHOLDER_MARK);

/** All files under public/images (recursive), as absolute paths. */
function listFiles(dir) {
  if (!existsSync(dir)) return [];
  return readdirSync(dir).flatMap((name) => {
    const path = join(dir, name);
    return statSync(path).isDirectory() ? listFiles(path) : [path];
  });
}

function check(strict) {
  const missing = [];
  const placeholders = [];
  let real = 0;
  for (const slot of slots) {
    const path = fileOf(slot);
    if (!existsSync(path)) missing.push(slot);
    else if (isPlaceholder(path)) placeholders.push(slot);
    else real += 1;
  }

  const expected = new Set(slots.map(fileOf));
  const ignored = new Set(["README.md", ".gitkeep"]);
  const stray = listFiles(IMAGES_DIR).filter((path) => !expected.has(path) && !ignored.has(path.split(sep).pop()));

  const line = (slot, note) => `  ${slot.src.padEnd(44)} ${`${slot.width}×${slot.height}`.padEnd(10)} ${note}`;
  console.log(`Image slots: ${slots.length} · real ${real} · placeholder ${placeholders.length} · missing ${missing.length}\n`);
  if (missing.length) {
    console.log(`MISSING (${missing.length}) — ImageSlot shows its "Image pending" box, the dev console logs a 404:`);
    missing.forEach((slot) => console.log(line(slot, imageUsage[slot.key])));
    console.log("");
  }
  if (placeholders.length) {
    console.log(`PLACEHOLDER — FAKE (${placeholders.length}) — generated dev image, replace with a real photo before launch:`);
    placeholders.forEach((slot) => console.log(line(slot, imageUsage[slot.key])));
    console.log("");
  }
  if (stray.length) {
    console.log(`NOT A SLOT (${stray.length}) — not referenced by content/images.ts (old flat path or a typo?):`);
    stray.forEach((path) => {
      const name = path.split(sep).pop().replace(/\.webp$/, "");
      const slot = images[name];
      console.log(`  ${rel(path)}${slot ? `  → move to ${slot.src.slice(1)}` : ""}`);
    });
    console.log("");
  }
  if (!missing.length && !placeholders.length) console.log("All slots have a real image.");
  if (strict && (missing.length || placeholders.length)) process.exit(1);
}

function readme() {
  const rows = slots.map(
    (slot) => `| \`${slot.folder}/${slot.key}.webp\` | ${slot.width} × ${slot.height} | ${ratio(slot)} | ${imageUsage[slot.key]} |`,
  );
  const reserved = IMAGE_FOLDERS.filter((folder) => !slots.some((slot) => slot.folder === folder));
  const md = [
    "# Site images",
    "",
    "<!-- GENERATED by `npm run images:readme` from content/images.ts. Do not edit by hand. -->",
    "",
    "Every image on the site is a slot in `content/images.ts`. To add or replace one, export a `.webp` at the size",
    "below (pre-compressed: there is no runtime image optimisation on static hosting) and save it under the exact",
    "folder/filename. No code change is needed; until the file exists the site shows a labelled \"Image pending\" box.",
    "",
    "- `npm run images:check` lists missing files and dev placeholders that still need a real photo.",
    "- `npm run images:placeholders` creates labelled placeholder files for missing slots only (never overwrites).",
    "- Logos live in `public/logo/`, not here. Never use a retail fuel-station photo.",
    "",
    `Folders: ${IMAGE_FOLDERS.map((folder) => `\`${folder}/\``).join(", ")}.` +
      (reserved.length ? ` Reserved for future pages (no slots yet): ${reserved.map((folder) => `\`${folder}/\``).join(", ")}.` : ""),
    "",
    "| File (public/images/…) | Size (px) | Aspect ratio | Where it appears |",
    "|---|---|---|---|",
    ...rows,
    "",
  ].join("\n");
  mkdirSync(IMAGES_DIR, { recursive: true });
  writeFileSync(join(IMAGES_DIR, "README.md"), md);
  console.log(`Wrote public/images/README.md (${slots.length} slots).`);
}

const escapeXml = (text) => text.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

/** Flat brand-tint card with a hairline frame + cross and the slot details written on it. */
function placeholderSvg(slot) {
  const { width: w, height: h } = slot;
  const u = Math.min(w, h) / 100;
  const text = (y, size, weight, fill, value) =>
    `<text x="50%" y="${y}" text-anchor="middle" font-family="Arial, Helvetica, sans-serif" font-size="${size}" font-weight="${weight}" fill="${fill}">${escapeXml(value)}</text>`;
  return `<svg xmlns="http://www.w3.org/2000/svg" width="${w}" height="${h}" viewBox="0 0 ${w} ${h}">
  <rect width="${w}" height="${h}" fill="#e8eff8"/>
  <rect x="${u * 2}" y="${u * 2}" width="${w - u * 4}" height="${h - u * 4}" fill="none" stroke="#0e4c9e" stroke-opacity="0.35" stroke-width="${u * 0.3}"/>
  <path d="M${u * 2} ${u * 2} L${w - u * 2} ${h - u * 2} M${w - u * 2} ${u * 2} L${u * 2} ${h - u * 2}" stroke="#0e4c9e" stroke-opacity="0.12" stroke-width="${u * 0.3}"/>
  ${text(h / 2 - u * 9, u * 3.6, 700, "#398d41", "PLACEHOLDER — REPLACE WITH REAL PHOTO")}
  ${text(h / 2 + u * 2, u * 8, 700, "#0e4c9e", slot.key)}
  ${text(h / 2 + u * 11, u * 3.6, 400, "#011433", `${slot.folder}/${slot.key}.webp · ${w} × ${h} · ${ratio(slot)}`)}
</svg>`;
}

async function placeholders() {
  let sharp;
  try {
    sharp = (await import("sharp")).default;
  } catch {
    console.error("sharp is not installed. Run `npm install` (it is a devDependency) and try again.");
    process.exit(1);
  }
  let created = 0;
  for (const slot of slots) {
    const path = fileOf(slot);
    if (existsSync(path)) continue; // never overwrite a real image (or an existing placeholder)
    mkdirSync(dirname(path), { recursive: true });
    const webp = await sharp(Buffer.from(placeholderSvg(slot)))
      .webp({ quality: 70 })
      .withExif({ IFD0: { ImageDescription: `${PLACEHOLDER_MARK} ${slot.key}` } })
      .toBuffer();
    writeFileSync(path, webp, { flag: "wx" });
    console.log(`  created ${rel(path)}`);
    created += 1;
  }
  console.log(created ? `\nCreated ${created} placeholder(s). They show up as PLACEHOLDER — FAKE in \`npm run images:check\`.` : "No missing slots; nothing created.");
}

/** TRD §10 weight budget (KB). Heroes and full-bleed backgrounds get the larger one. */
const budgetKb = (slot) => (slot.folder === "home/hero" || /(^|-)hero($|-)|^cta-bg$/.test(slot.key) ? 200 : 120);
const maxWidth = (slot) => (budgetKb(slot) === 200 ? 1600 : 1200);

/**
 * Re-encodes real (non-placeholder) photos that are over budget: caps the width, then lowers WebP quality
 * until the file fits. Files already within budget are never touched. Needs `sharp` (devDependency).
 */
async function optimize(dry) {
  const { default: sharp } = await import("sharp");
  let touched = 0;
  for (const slot of slots) {
    const path = fileOf(slot);
    if (!existsSync(path) || isPlaceholder(path)) continue;
    const before = statSync(path).size;
    const budget = budgetKb(slot) * 1024;
    if (before <= budget) continue;
    const input = readFileSync(path);
    const meta = await sharp(input).metadata();
    const width = Math.min(meta.width ?? maxWidth(slot), maxWidth(slot));
    let best = null;
    for (let quality = 80; quality >= 40; quality -= 5) {
      best = await sharp(input).resize({ width, withoutEnlargement: true }).webp({ quality, effort: 6, alphaQuality: 80 }).toBuffer();
      if (best.length <= budget) break;
    }
    const kb = (n) => `${Math.round(n / 1024)}KB`;
    console.log(`${rel(path).padEnd(52)} ${kb(before).padStart(6)} -> ${kb(best.length).padStart(6)}${best.length > budget ? "  (still over budget)" : ""}`);
    if (!dry) writeFileSync(path, best);
    touched += 1;
  }
  console.log(`${touched} file(s) ${dry ? "would be " : ""}optimized.`);
}

const [command, ...flags] = process.argv.slice(2);
if (command === "check") check(flags.includes("--strict"));
else if (command === "readme") readme();
else if (command === "placeholders") await placeholders();
else if (command === "optimize") await optimize(flags.includes("--dry"));
else {
  console.error("Usage: node scripts/images.mjs <check [--strict] | readme | placeholders | optimize [--dry]>");
  process.exit(1);
}
