// SEO / structured-data audit over the static export. Run after `npm run build`:  npm run seo:audit
// Reads out/**/*.html (no server needed). Exits 1 when any check fails.
import fs from "node:fs";
import path from "node:path";

const OUT = path.resolve("out");
const SITE_URL = (process.env.NEXT_PUBLIC_SITE_URL || "https://www.indoxenergy.com").replace(/\/$/, "");

if (!fs.existsSync(OUT)) {
  console.error("out/ not found. Run `npm run build` first.");
  process.exit(1);
}

// ---------- collect pages ----------
function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((e) => {
    const full = path.join(dir, e.name);
    if (e.isDirectory()) return e.name === "_next" || e.name === "images" || e.name === "logo" ? [] : walk(full);
    return e.name.endsWith(".html") ? [full] : [];
  });
}

const rel = (file) => path.relative(OUT, file).split(path.sep).join("/");
const routeOf = (file) => {
  const r = rel(file);
  if (r === "404.html") return "404";
  return r === "index.html" ? "/" : `/${r.replace(/index\.html$/, "")}`;
};

const pages = walk(OUT)
  // out/404/index.html is Next's duplicate of 404.html
  .filter((f) => rel(f) !== "404/index.html")
  .map((file) => {
    const html = fs.readFileSync(file, "utf8");
    // Scripts hold the RSC payload, which contains markup-looking strings; strip them for DOM-level checks.
    const dom = html.replace(/<script\b[\s\S]*?<\/script>/gi, "").replace(/<style\b[\s\S]*?<\/style>/gi, "");
    return { file, route: routeOf(file), html, dom };
  });

const failures = [];
const fail = (route, msg) => failures.push(`${route}  ${msg}`);
const decode = (s) => s.replace(/&amp;/g, "&").replace(/&quot;/g, '"').replace(/&#x27;/g, "'").replace(/&#39;/g, "'").replace(/&lt;/g, "<").replace(/&gt;/g, ">");

const attr = (tag, name) => {
  const m = tag.match(new RegExp(`\\s${name}\\s*=\\s*("([^"]*)"|'([^']*)'|([^\\s>]+))`, "i"));
  return m ? decode(m[2] ?? m[3] ?? m[4] ?? "") : null;
};
const tagsOf = (dom, name) => dom.match(new RegExp(`<${name}\\b[^>]*>`, "gi")) ?? [];

// ---------- titles, descriptions, h1, canonical, images ----------
const titles = new Map();
const descriptions = new Map();

for (const { route, dom } of pages) {
  const titleMatch = dom.match(/<title[^>]*>([\s\S]*?)<\/title>/i);
  const title = titleMatch ? decode(titleMatch[1]).trim() : "";
  if (!title) fail(route, "missing <title>");
  else if (/^(create next app|indox energy)$/i.test(title)) fail(route, `default <title> "${title}"`);
  else titles.set(title, [...(titles.get(title) ?? []), route]);

  const desc = tagsOf(dom, "meta").find((t) => attr(t, "name") === "description");
  const description = desc ? (attr(desc, "content") ?? "").trim() : "";
  if (!description) fail(route, "missing meta description");
  else if (/generated by create next app/i.test(description)) fail(route, "default meta description");
  else descriptions.set(description, [...(descriptions.get(description) ?? []), route]);

  const h1s = (dom.match(/<h1\b/gi) ?? []).length;
  if (h1s !== 1) fail(route, `expected exactly one <h1>, found ${h1s}`);

  for (const img of tagsOf(dom, "img")) {
    const alt = attr(img, "alt");
    // Purely decorative background photos are alt="" + aria-hidden="true" (correct a11y); anything else needs real alt text.
    const decorative = alt === "" && (attr(img, "aria-hidden") === "true" || attr(img, "role") === "presentation");
    if (!decorative && (alt === null || !alt.trim())) fail(route, `<img> without alt text: ${(attr(img, "src") ?? "").slice(0, 80)}`);
  }

  const canon = tagsOf(dom, "link").filter((t) => attr(t, "rel") === "canonical");
  if (route === "404") {
    if (canon.length) fail(route, "404 page must not declare a canonical");
  } else if (canon.length !== 1) {
    fail(route, `expected one canonical, found ${canon.length}`);
  } else {
    const href = attr(canon[0], "href") ?? "";
    if (!/^https?:\/\//.test(href)) fail(route, `canonical is not absolute: ${href}`);
    else if (!href.endsWith("/")) fail(route, `canonical lacks trailing slash: ${href}`);
    else if (href !== `${SITE_URL}${route}`) fail(route, `canonical ${href} != ${SITE_URL}${route}`);
  }

  // Page-level robots: only /thank-you/ and 404 may be noindex.
  const noindex = tagsOf(dom, "meta").some((t) => attr(t, "name") === "robots" && /noindex/i.test(attr(t, "content") ?? ""));
  const shouldNoindex = route === "/thank-you/" || route === "404";
  if (noindex !== shouldNoindex) fail(route, shouldNoindex ? "must be noindex" : "is noindex but should be indexable");
}
for (const [title, routes] of titles) if (routes.length > 1) fail(routes.join(", "), `duplicate <title> "${title}"`);
for (const [d, routes] of descriptions) if (routes.length > 1) fail(routes.join(", "), `duplicate meta description "${d.slice(0, 60)}…"`);

// ---------- internal links ----------
const idCache = new Map();
const idsOf = (file) => {
  if (!idCache.has(file)) {
    const html = fs.readFileSync(file, "utf8").replace(/<script\b[\s\S]*?<\/script>/gi, "");
    idCache.set(file, new Set([...html.matchAll(/\sid="([^"]+)"/g)].map((m) => m[1])));
  }
  return idCache.get(file);
};

function resolveTarget(pathname) {
  const clean = decodeURIComponent(pathname);
  if (clean.endsWith("/")) return path.join(OUT, clean, "index.html");
  return path.join(OUT, clean);
}

let linkCount = 0;
for (const { route, dom } of pages) {
  const refs = [
    ...tagsOf(dom, "a").map((t) => ({ kind: "href", value: attr(t, "href"), tag: t })),
    ...tagsOf(dom, "link").map((t) => ({ kind: "href", value: attr(t, "href"), tag: t })),
    ...tagsOf(dom, "img").map((t) => ({ kind: "src", value: attr(t, "src"), tag: t })),
    ...tagsOf(dom, "iframe").map((t) => ({ kind: "src", value: attr(t, "src"), tag: t })),
  ];
  for (const { kind, value, tag } of refs) {
    if (value === null) {
      if (kind === "href" && /^<a\b/i.test(tag)) fail(route, `<a> without href: ${tag.slice(0, 80)}`);
      continue;
    }
    if (kind === "href" && /^<a\b/i.test(tag) && (value.trim() === "#" || value.trim() === "")) {
      fail(route, `link points to "${value}"`);
      continue;
    }
    if (/^(mailto:|tel:|https?:\/\/(?!(www\.)?indoxenergy\.com)|data:|javascript:)/i.test(value)) continue;
    if (value.startsWith("//")) continue;
    let target = value;
    if (target.startsWith(SITE_URL)) target = target.slice(SITE_URL.length) || "/";
    if (/^https?:/i.test(target)) continue;
    if (!target.startsWith("/") && !target.startsWith("#") && !target.startsWith("?")) continue; // relative asset noise, none expected
    linkCount++;
    const url = new URL(target, `${SITE_URL}${route === "404" ? "/" : route}`);
    const isRoute = url.pathname.endsWith("/");
    const file = resolveTarget(url.pathname);
    if (!fs.existsSync(file)) {
      fail(route, `broken internal ${kind}: ${value}`);
      continue;
    }
    if (isRoute && url.hash.length > 1 && /^<a\b/i.test(tag)) {
      const id = decodeURIComponent(url.hash.slice(1));
      if (!idsOf(file).has(id)) fail(route, `anchor target missing: ${value}`);
    }
  }
}

// ---------- JSON-LD ----------
const isAbs = (s) => typeof s === "string" && /^https?:\/\//.test(s);
function ldOf(html) {
  const out = [];
  for (const m of html.matchAll(/<script type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/g)) {
    try {
      out.push(JSON.parse(m[1]));
    } catch (e) {
      out.push({ __invalid: String(e) });
    }
  }
  return out.flatMap((x) => (Array.isArray(x) ? x : [x]));
}

function validateNode(route, node) {
  if (node.__invalid) return fail(route, `JSON-LD is not valid JSON (${node.__invalid})`);
  if (node["@context"] !== "https://schema.org") fail(route, `JSON-LD ${node["@type"]}: bad @context`);
  const need = (cond, msg) => cond || fail(route, `JSON-LD ${node["@type"]}: ${msg}`);
  switch (node["@type"]) {
    case "Organization":
      need(node.name && node.url && node.logo, "needs name, url, logo");
      break;
    case "LocalBusiness":
      need(node.name && node.url && node.telephone, "needs name, url, telephone");
      break;
    case "Product":
      need(node.name && node.description && isAbs(node.image) && isAbs(node.url), "needs name, description, absolute image + url");
      need(!("offers" in node), "must not carry offers/price");
      break;
    case "Service":
      need(node.name && node.description && node.provider && node.areaServed, "needs name, description, provider, areaServed");
      break;
    case "Article":
      need(node.headline && node.datePublished && node.author?.name && isAbs(node.image), "needs headline, datePublished, author, absolute image");
      need(!Number.isNaN(Date.parse(node.datePublished)), "datePublished is not a date");
      break;
    case "FAQPage":
      need(Array.isArray(node.mainEntity) && node.mainEntity.length > 0, "empty mainEntity");
      for (const q of node.mainEntity ?? []) need(q.name && q.acceptedAnswer?.text, "question without name / answer text");
      break;
    case "BreadcrumbList":
      need(Array.isArray(node.itemListElement) && node.itemListElement.length >= 2, "needs at least 2 items");
      (node.itemListElement ?? []).forEach((it, i) => need(it.position === i + 1 && it.name && isAbs(it.item) && it.item.endsWith("/"), `item ${i + 1} invalid`));
      break;
    case "ContactPage":
      need(node.name && isAbs(node.url), "needs name and absolute url");
      break;
    default:
      fail(route, `unexpected JSON-LD type ${node["@type"]}`);
  }
}

for (const { route, html } of pages) {
  const nodes = ldOf(html);
  nodes.forEach((n) => validateNode(route, n));
  const types = new Set(nodes.map((n) => n["@type"]));
  const expect = (type) => types.has(type) || fail(route, `missing JSON-LD ${type}`);

  if (route !== "404") {
    expect("Organization");
    expect("LocalBusiness");
  }
  // /thank-you/ has no breadcrumb trail (noindex, reached only after a submit).
  const inner = route !== "/" && route !== "404" && route !== "/thank-you/";
  if (inner) expect("BreadcrumbList");
  if (route.startsWith("/products/") && route !== "/products/") {
    expect("Product");
    expect("FAQPage");
  }
  if (route.startsWith("/services/") && route !== "/services/") {
    expect("Service");
    expect("FAQPage");
  }
  if (route === "/ev-charging/") {
    expect("Service");
    expect("FAQPage");
  }
  if (route.startsWith("/blog/") && route !== "/blog/") expect("Article");
  if (route === "/contact/") expect("ContactPage");
  // Any page that renders an FAQ block must ship FAQPage data.
  if (route !== "404" && /id="faq/i.test(html) && !types.has("FAQPage")) fail(route, "FAQ block without FAQPage JSON-LD");
}

// ---------- sitemap + robots ----------
const sitemapFile = path.join(OUT, "sitemap.xml");
const robotsFile = path.join(OUT, "robots.txt");
const sitemapUrls = fs.existsSync(sitemapFile) ? [...fs.readFileSync(sitemapFile, "utf8").matchAll(/<loc>([^<]+)<\/loc>/g)].map((m) => m[1]) : [];
if (!sitemapUrls.length) fail("sitemap.xml", "missing or empty");
const indexable = pages.filter((p) => p.route !== "404" && p.route !== "/thank-you/").map((p) => `${SITE_URL}${p.route}`);
for (const url of indexable) if (!sitemapUrls.includes(url)) fail("sitemap.xml", `missing indexable page ${url}`);
for (const url of sitemapUrls) if (!indexable.includes(url)) fail("sitemap.xml", `lists a URL that is not an indexable page: ${url}`);
if (new Set(sitemapUrls).size !== sitemapUrls.length) fail("sitemap.xml", "duplicate entries");
if (sitemapUrls.length !== 28) fail("sitemap.xml", `expected 28 URLs, found ${sitemapUrls.length}`);

const robots = fs.existsSync(robotsFile) ? fs.readFileSync(robotsFile, "utf8") : "";
if (!robots.includes(`Sitemap: ${SITE_URL}/sitemap.xml`)) fail("robots.txt", "does not reference the sitemap");
const disallowed = [...robots.matchAll(/^Disallow:\s*(\S+)/gim)].map((m) => m[1]);
for (const d of disallowed) if (d !== "/thank-you/") fail("robots.txt", `unexpected Disallow: ${d}`);
if (disallowed.includes("/")) fail("robots.txt", "blocks the whole site");

// ---------- .htaccess / 404.html ----------
if (!fs.existsSync(path.join(OUT, "404.html"))) fail("404.html", "not exported");
const htaccess = fs.existsSync(path.join(OUT, ".htaccess")) ? fs.readFileSync(path.join(OUT, ".htaccess"), "utf8") : "";
if (!/^ErrorDocument 404 \/404\.html\s*$/m.test(htaccess)) fail(".htaccess", 'missing "ErrorDocument 404 /404.html"');

// ---------- summary ----------
console.log(`Pages audited: ${pages.length} (${indexable.length} indexable, sitemap ${sitemapUrls.length})`);
console.log(`Internal links/assets checked: ${linkCount}`);
console.log(`Unique titles: ${titles.size}, unique descriptions: ${descriptions.size}`);
if (failures.length) {
  console.log(`\nFAIL: ${failures.length} problem(s)`);
  for (const f of failures) console.log(`  - ${f}`);
  process.exit(1);
}
console.log("\nPASS: all SEO checks passed");
